# Repelling and attracting LCS as strain tensor lines

The FTLE map (see `cabo_verde_ftle`) shows *where* the flow stretches, but not
the material curves along which it does. Those curves are tensor lines of the
strain tensor. Haller (2015, §5.1 / Table 1,
[doi:10.1146/annurev-fluid-010313-141322](https://doi.org/10.1146/annurev-fluid-010313-141322))
constructs those curves directly from the Cauchy–Green strain tensor
$C = (\nabla F)^\top \nabla F$, whose eigenpairs satisfy
$C\,\xi_i = \lambda_i\,\xi_i$ with $0 < \lambda_1 \le \lambda_2$ and
$\xi_1 \perp \xi_2$. A **repelling** LCS is a *shrink line* — a curve tangent
to $\xi_1$, i.e. orthogonal to the strong-stretch direction $\xi_2$ that the
FTLE ridge marks. It solves the ODE $\dot r = \xi_1(r)$.

Attracting LCS come from the forward–backward duality (Haller & Sapsis 2011,
[doi:10.1063/1.3579597](https://doi.org/10.1063/1.3579597)): an **attracting**
LCS is a repelling LCS of the *backward* flow. So we advect the same seed grid
both ways and take the $\xi_1$ shrink lines of each flow map — forward for
repelling, backward for attracting.

In [1]:
import matplotlib.pyplot as plt
import numpy as np
import xarray as xr
from parcels import FieldSet, Particle, ParticleSet, StatusCode
from parcels.convert import copernicusmarine_to_sgrid
from parcels.kernels import AdvectionRK4

from lcs_parcels import NeighborSeed, ftle_ridge_seeds, shrink_lines

/var/folders/w1/m9mm9h9167z_gcfzfffr0rgsh6j6kj/T/ipykernel_4767/3232594537.py:4: UserWarning: This is an alpha version of Parcels v4. The API is not stable and may change without deprecation warnings.
  from parcels import FieldSet, Particle, ParticleSet, StatusCode


## Currents

The local file that `get_data` writes.

In [2]:
currents = xr.open_dataset("data/cabo_verde_currents_hourly.nc").load()
currents

<xarray.Dataset> Size: 53MB
Dimensions:    (time: 289, depth: 1, latitude: 145, longitude: 157)
Coordinates:
  * time       (time) datetime64[ns] 2kB 2025-07-31 ... 2025-08-12
  * depth      (depth) float32 4B 0.494
  * latitude   (latitude) float32 580B 10.0 10.08 10.17 ... 21.83 21.92 22.0
  * longitude  (longitude) float32 628B -30.5 -30.42 -30.33 ... -17.58 -17.5
Data variables:
    uo         (time, depth, latitude, longitude) float32 26MB 0.144 ... -0.1622
    vo         (time, depth, latitude, longitude) float32 26MB -0.1292 ... -0...
Attributes:
    Conventions:               CF-1.8
    area:                      Global
    contact:                   https://marine.copernicus.eu/contact
    credit:                    E.U. Copernicus Marine Service Information (CM...
    institution:               Mercator Ocean International
    licence:                   http://marine.copernicus.eu/services-portfolio...
    producer:                  CMEMS - Global Monitoring and Forecasting Centre
    references:                http://marine.copernicus.eu
    source:                    MOI GLO12
    title:                     hourly mean fields from Global Ocean Physics A...
    copernicusmarine_version:  2.4.1

## Parcels v4 field set

`copernicusmarine_to_sgrid` tags the CMEMS A-grid with SGRID metadata;
`from_sgrid_conventions` wraps it as a spherical `FieldSet`.

In [3]:
sgrid = copernicusmarine_to_sgrid(fields={"U": currents["uo"], "V": currents["vo"]})
fieldset = FieldSet.from_sgrid_conventions(sgrid, mesh="spherical")
z_surface = float(currents["depth"].values[0])

## Seed grid and window

We anchor at the middle of the window the local file covers and run $\pm 5$ d,
so the forward and the backward advection both stay inside the data. A
rectilinear `NeighborSeed` puts one particle on every diagnostic grid point;
$\nabla F$ is then differenced against the grid neighbours.

In [4]:
t0 = np.datetime64("2025-08-06")
T = np.timedelta64(5, "D")
resolution_deg = 1 / 25
seed_lon, seed_lat = (-27.0, -21.0), (13.5, 18.5)

lon_axis = np.arange(seed_lon[0], seed_lon[1] + 1e-9, resolution_deg)
lat_axis = np.arange(seed_lat[0], seed_lat[1] + 1e-9, resolution_deg)
seed = NeighborSeed.from_axes(lon=lon_axis, lat=lat_axis)
seed

<NeighborSeed 151x126 grid, lon -27.00..-21.00, lat 13.50..18.50>

## Recovery kernel

Particles that leave the domain or hit land are turned into `NaN` in place
(Parcels would otherwise abort the run), so losses propagate as `NaN` through
every diagnostic below. `StatusCode.EndofLoop` rather than
`StatusCode.Delete`: deleting shrinks the particle array and breaks the
alignment with the seed order.

In [5]:
def set_lost_to_nan(particles, fieldset):
    lost = particles.state >= StatusCode.Error
    particles.x = np.where(lost, np.nan, particles.x)
    particles.y = np.where(lost, np.nan, particles.y)
    particles.state = np.where(lost, StatusCode.EndofLoop, particles.state)

## Advect forward

`to_parcels_pset` emits the flat `(lon, lat)` pair; the finals go back in via
`pset_to_flowmap`, which takes both times and derives the signed window
$T = t_1 - t_0$.

In [6]:
lon, lat = seed.to_parcels_pset()
z = np.full(len(lon), z_surface)
pset = ParticleSet(fieldset, pclass=Particle, x=lon, y=lat, z=z, t=t0)
pset.execute(
    [AdvectionRK4, set_lost_to_nan],
    dt=np.timedelta64(1, "h"),
    runtime=T,
)
forward = seed.pset_to_flowmap(lon=pset.x, lat=pset.y, t0=t0, t1=t0 + T)
forward

   0%|          | [00:00<?, ?it/s]

Integration time: 2025-08-06T00:00:00   0%|          | [00:00<?, ?it/s]

Integration time: 2025-08-06T00:00:00   0%|          | [00:02<?, ?it/s]

Integration time: 2025-08-06T00:00:00 100%|██████████| [00:02<00:00, 176728.46it/s]

Integration time: 2025-08-06T00:00:00 100%|██████████| [00:02<00:00, 176706.92it/s]

<NeighborFlowMap 151x126 grid, lon -27.00..-21.00, lat 13.50..18.50, t0 2025-08-06T00:00:00, T +5.0 days>

## Advect backward

The same seed grid, same $t_0$, negative `dt`, and $t_1 = t_0 - T$ so the
stored window is negative.

In [7]:
lon, lat = seed.to_parcels_pset()
z = np.full(len(lon), z_surface)
pset = ParticleSet(fieldset, pclass=Particle, x=lon, y=lat, z=z, t=t0)
pset.execute(
    [AdvectionRK4, set_lost_to_nan],
    dt=-np.timedelta64(1, "h"),
    runtime=T,
)
backward = seed.pset_to_flowmap(lon=pset.x, lat=pset.y, t0=t0, t1=t0 - T)
backward

   0%|          | [00:00<?, ?it/s]

Integration time: 2025-08-06T00:00:00   0%|          | [00:00<?, ?it/s]

Integration time: 2025-08-06T00:00:00   0%|          | [00:02<?, ?it/s]

Integration time: 2025-08-06T00:00:00 100%|██████████| [00:02<00:00, 177891.31it/s]

Integration time: 2025-08-06T00:00:00 100%|██████████| [00:02<00:00, 177872.48it/s]

<NeighborFlowMap 151x126 grid, lon -27.00..-21.00, lat 13.50..18.50, t0 2025-08-06T00:00:00, T -5.0 days>

## Repelling LCS, step by step

The forward FTLE (from $\lambda_2$ of the forward $C$) is the backdrop and its
ridges are where repelling LCS live.

In [8]:
ftle_forward = forward.ftle()
ftle_forward

<xarray.DataArray 'ftle' (i: 151, j: 126)> Size: 152kB
array([[           nan,            nan,            nan, ...,
                   nan,            nan,            nan],
       [           nan, 1.34604789e-06, 1.22454554e-06, ...,
        4.33853722e-07, 4.74550783e-07,            nan],
       [           nan, 1.48441260e-06, 1.35844747e-06, ...,
        4.62888133e-07, 5.25117251e-07,            nan],
       ...,
       [           nan, 4.71279824e-07, 5.19261299e-07, ...,
        1.47111824e-06, 1.43368754e-06,            nan],
       [           nan, 5.10593880e-07, 6.05760742e-07, ...,
        1.56342352e-06, 1.54052956e-06,            nan],
       [           nan,            nan,            nan, ...,
                   nan,            nan,            nan]], shape=(151, 126))
Coordinates:
  * i         (i) int64 1kB 0 1 2 3 4 5 6 7 ... 143 144 145 146 147 148 149 150
  * j         (j) int64 1kB 0 1 2 3 4 5 6 7 ... 118 119 120 121 122 123 124 125
    lon_grid  (i, j) float64 152kB -27.0 -27.0 -27.0 -27.0 ... -21.0 -21.0 -21.0
    lat_grid  (i, j) float64 152kB 13.5 13.54 13.58 13.62 ... 18.42 18.46 18.5
    t0        datetime64[s] 8B 2025-08-06
    T         timedelta64[s] 8B 5 days
Attributes:
    units:      1/s
    long_name:  finite-time Lyapunov exponent

`ftle_ridge_seeds` picks start points at the ridge tops: grid points that are
the maximum over a `window_m`-wide neighbourhood and lie in the top `quantile`
of the field. The window is the full width, so two seeds cannot be closer than
about half of it. We want neighbouring filaments about 15 km apart in this eddy
field, which is three to four cells of the 1/25-degree seed grid, so the window
is 30 km. The top decile keeps the seeds on the pronounced ridges of *this*
field.

In [9]:
# Ridge selection.
window_m, quantile = 30_000.0, 0.90

In [10]:
repelling_seed_lon, repelling_seed_lat = ftle_ridge_seeds(
    ftle_forward, window_m=window_m, quantile=quantile
)
repelling_seed_lon.shape, repelling_seed_lon[:5], repelling_seed_lat[:5]

((54,),
 array([-26.96, -26.68, -26.52, -26.28, -26.12]),
 array([16.02, 14.22, 16.46, 15.66, 16.22]))

`shrink_lines` integrates $\dot r = \xi_1(r)$ through each seed, half the
length either way. The 3 km step is below the ~4.4 km seed-grid cell, so the
RK2 trace samples every cell it crosses; the 1500 km cap is longer than the box
diagonal,
so what actually ends a curve is leaving the grid, hitting a NaN cell, or
`min_anisotropy` — the floor on $\lambda_2 / \lambda_1$ below which $\xi_1$ is
no longer a well-defined direction. Being a ratio, it is free of the window and
of the flow's own stretching rate, so the 1.15 default carries over unchanged
from a longer window or a faster flow.

In [11]:
# Line integration.
step_m, line_length_m, min_anisotropy = 3_000.0, 1_500_000.0, 1.15

In [12]:
repelling_lcs = shrink_lines(
    forward,
    seed_lon=repelling_seed_lon,
    seed_lat=repelling_seed_lat,
    step_m=step_m,
    line_length_m=line_length_m,
    min_anisotropy=min_anisotropy,
)
repelling_lcs

<xarray.Dataset> Size: 437kB
Dimensions:  (line: 54, point: 501)
Coordinates:
  * line     (line) int64 432B 0 1 2 3 4 5 6 7 8 ... 45 46 47 48 49 50 51 52 53
  * point    (point) int64 4kB 0 1 2 3 4 5 6 7 ... 494 495 496 497 498 499 500
Data variables:
    lon      (line, point) float64 216kB nan nan nan nan nan ... nan nan nan nan
    lat      (line, point) float64 216kB nan nan nan nan nan ... nan nan nan nan

The lines are a fixed `(line, point)` rectangle, NaN-padded past termination:
same number of columns, different curve lengths.

In [13]:
repelling_lcs["lon"].isnull().sum("point")

<xarray.DataArray 'lon' (line: 54)> Size: 432B
array([484, 369, 401, 399, 400, 445, 412, 441, 451, 361, 501, 359, 501,
       188, 360, 183, 231, 501, 354, 327, 472, 498, 483, 441, 360, 330,
       501, 359, 501, 434, 397, 418, 501, 501, 431, 501, 440, 455, 322,
       501, 501, 328, 501, 300, 501, 501, 453, 501, 379, 373, 373, 350,
       419, 501])
Coordinates:
  * line     (line) int64 432B 0 1 2 3 4 5 6 7 8 ... 45 46 47 48 49 50 51 52 53
Attributes:
    long_name:  longitude along the shrink line
    units:      degrees_east

Rows that are NaN in every column traced no curve at all. About a quarter of
the seeds here sit close to land, so the interpolated tensor is NaN at the seed
and no LCS materialises.

In [14]:
untraceable = repelling_lcs["lon"].isnull().all("point")
int(untraceable.sum()), repelling_lcs.sizes["line"]

(15, 54)

## Attracting LCS, in one call

The backward flow map runs the identical three steps, so we let
`hyperbolic_lcs` do it: it computes the FTLE once, hands it to the ridge
finder, and returns the curves together with the field they were picked from.
*Hyperbolic* because elliptic LCS are a different family.

In [15]:
attracting_lcs = backward.hyperbolic_lcs(
    window_m=window_m,
    quantile=quantile,
    step_m=step_m,
    line_length_m=line_length_m,
    min_anisotropy=min_anisotropy,
)
attracting_lcs

<xarray.Dataset> Size: 872kB
Dimensions:   (line: 51, point: 501, i: 151, j: 126)
Coordinates:
  * line      (line) int64 408B 0 1 2 3 4 5 6 7 8 ... 42 43 44 45 46 47 48 49 50
  * point     (point) int64 4kB 0 1 2 3 4 5 6 7 ... 494 495 496 497 498 499 500
  * i         (i) int64 1kB 0 1 2 3 4 5 6 7 ... 143 144 145 146 147 148 149 150
  * j         (j) int64 1kB 0 1 2 3 4 5 6 7 ... 118 119 120 121 122 123 124 125
    lon_grid  (i, j) float64 152kB -27.0 -27.0 -27.0 -27.0 ... -21.0 -21.0 -21.0
    lat_grid  (i, j) float64 152kB 13.5 13.54 13.58 13.62 ... 18.42 18.46 18.5
    t0        datetime64[s] 8B 2025-08-06
    T         timedelta64[s] 8B -5 days
Data variables:
    lon       (line, point) float64 204kB nan nan nan nan ... nan nan nan nan
    lat       (line, point) float64 204kB nan nan nan nan ... nan nan nan nan
    ftle      (i, j) float64 152kB nan nan nan nan nan ... nan nan nan nan nan
Attributes:
    long_name:  attracting LCS: shrink lines of the backward flow map, with t...

## Repelling LCS over the forward FTLE

The seed points are dotted so we can check they sit on the ridge tops and stay
separated. The FTLE gets a greyscale so the curves read against it. The dots
with no curve through them are the untraceable seeds counted above.

In [16]:
fig, ax = plt.subplots()
ftle_forward.plot.pcolormesh(x="lon_grid", y="lat_grid", ax=ax, cmap="Greys")
ax.plot(
    repelling_lcs["lon"].values.T,
    repelling_lcs["lat"].values.T,
    color="tab:red",
    lw=0.8,
)
ax.scatter(repelling_seed_lon, repelling_seed_lat, s=8, color="tab:red")

## Attracting LCS over the backward FTLE

Same picture for the backward flow map, straight out of the one dataset
`hyperbolic_lcs` returned.

In [17]:
fig, ax = plt.subplots()
attracting_lcs["ftle"].plot.pcolormesh(x="lon_grid", y="lat_grid", ax=ax, cmap="Greys")
ax.plot(
    attracting_lcs["lon"].values.T,
    attracting_lcs["lat"].values.T,
    color="tab:blue",
    lw=0.8,
)

## Both families together

Both families over the forward FTLE, in one frame: where a repelling and an
attracting curve cross, the flow is locally hyperbolic.

In [18]:
fig, ax = plt.subplots()
ftle_forward.plot.pcolormesh(x="lon_grid", y="lat_grid", ax=ax, cmap="Greys")
ax.plot(
    repelling_lcs["lon"].values.T,
    repelling_lcs["lat"].values.T,
    color="tab:red",
    lw=0.8,
)
ax.plot(
    attracting_lcs["lon"].values.T,
    attracting_lcs["lat"].values.T,
    color="tab:blue",
    lw=0.8,
)