# Seed grids and flow maps

This notebook is about the structures and the API, not about advection.

A `SeedGrid` holds a grid of release positions. `SeedGrid.to_parcels_pset()`
emits them as flat `lon`, `lat` lists. `SeedGrid.pset_to_flowmap(...)` ingests the
advected positions and returns a `FlowMap`, which computes the deformation
gradient, the Cauchy–Green tensor, and the FTLE. No Parcels is imported below,
and the advection is replaced by particles that do not move.

Three pairs of classes follow. `NeighborSeedGrid` releases one particle per
grid point and differences against the neighbouring grid points.
`AuxiliarySeedGrid` releases four arms around each grid point and differences
across the arms. `UnstructuredAuxiliarySeedGrid` lays the same four arms around
grid points that need not sit on a mesh at all.

In [1]:
import numpy as np

from lcs_parcels import (
    AuxiliarySeedGrid,
    NeighborSeedGrid,
    UnstructuredAuxiliarySeedGrid,
)

## Grid and window

The axes set the grid. The times are not attached to anything until ingest.
`t1 > t0` makes the window $T = t_1 - t_0$ positive, so the FTLE below is the
forward one.

In [2]:
lon_axis = np.linspace(-25.0, -20.0, 6)
lat_axis = np.linspace(15.0, 20.0, 5)

t0 = np.datetime64("2020-01-01")
t1 = np.datetime64("2020-01-11")

## The neighbour stencil

The neighbour stencil releases one particle per grid point. The release
positions `lon_0`/`lat_0` *are* the diagnostic grid points `lon_grid`/`lat_grid`,
stored twice rather than left to be reconstructed. The outermost ring of grid
points has no neighbour to difference against on one side, so the FTLE is
undefined there.

In [3]:
seed = NeighborSeedGrid.from_axes(lon=lon_axis, lat=lat_axis)
print(seed)
seed.ds

<NeighborSeedGrid 6x5 grid, lon -25.00..-20.00, lat 15.00..20.00>


<xarray.Dataset> Size: 1kB
Dimensions:   (i: 6, j: 5)
Coordinates:
  * i         (i) int64 48B 0 1 2 3 4 5
  * j         (j) int64 40B 0 1 2 3 4
    lon_grid  (i, j) float64 240B -25.0 -25.0 -25.0 -25.0 ... -20.0 -20.0 -20.0
    lat_grid  (i, j) float64 240B 15.0 16.25 17.5 18.75 ... 17.5 18.75 20.0
    lon_0     (i, j) float64 240B -25.0 -25.0 -25.0 -25.0 ... -20.0 -20.0 -20.0
    lat_0     (i, j) float64 240B 15.0 16.25 17.5 18.75 ... 17.5 18.75 20.0
Data variables:
    *empty*

## The auxiliary stencil

Four arms (`east, north, west, south`) sit at `aux_separation_m` around each
grid point. `lon_0`/`lat_0` gain a `displacement` dim, and each grid point
releases four particles. The finite-difference step is the arm separation
rather than the grid spacing, and the FTLE is defined at every grid point,
including the boundary.

In [4]:
aux_seed = AuxiliarySeedGrid.from_axes(
    lon=lon_axis, lat=lat_axis, aux_separation_m=1_000.0
)
print(aux_seed)
aux_seed.ds

<AuxiliarySeedGrid 6x5 grid, lon -25.00..-20.00, lat 15.00..20.00>


<xarray.Dataset> Size: 3kB
Dimensions:       (displacement: 4, i: 6, j: 5)
Coordinates:
  * displacement  (displacement) <U5 80B 'east' 'north' 'west' 'south'
    lon_0         (i, j, displacement) float64 960B -24.99 -25.0 ... -20.0
    lat_0         (i, j, displacement) float64 960B 15.0 15.01 ... 20.0 19.99
  * i             (i) int64 48B 0 1 2 3 4 5
  * j             (j) int64 40B 0 1 2 3 4
    lon_grid      (i, j) float64 240B -25.0 -25.0 -25.0 ... -20.0 -20.0 -20.0
    lat_grid      (i, j) float64 240B 15.0 16.25 17.5 18.75 ... 17.5 18.75 20.0
Data variables:
    *empty*

## The unstructured auxiliary stencil

The same four arms sit around grid points handed over as two flat arrays
instead of two axes. The arm differencing never looks at another grid point,
so nothing downstream of it needs the points to line up. Here they are drawn
at random inside the same box.

In [5]:
rng = np.random.default_rng(0)
point_lon = rng.uniform(lon_axis[0], lon_axis[-1], 30)
point_lat = rng.uniform(lat_axis[0], lat_axis[-1], 30)

scattered_seed = UnstructuredAuxiliarySeedGrid.from_points(
    lon=point_lon, lat=point_lat, aux_separation_m=1_000.0
)
print(scattered_seed)
scattered_seed.ds

<UnstructuredAuxiliarySeedGrid 30 grid, lon -24.99..-20.01, lat 15.26..19.67>


<xarray.Dataset> Size: 3kB
Dimensions:       (displacement: 4, grid_point: 30)
Coordinates:
  * displacement  (displacement) <U5 80B 'east' 'north' 'west' 'south'
    lon_0         (grid_point, displacement) float64 960B -21.81 ... -21.75
    lat_0         (grid_point, displacement) float64 960B 18.44 18.45 ... 15.25
  * grid_point    (grid_point) int64 240B 0 1 2 3 4 5 6 ... 23 24 25 26 27 28 29
    lon_grid      (grid_point) float64 240B -21.82 -23.65 ... -21.57 -21.75
    lat_grid      (grid_point) float64 240B 18.44 16.94 15.68 ... 16.15 15.26
Data variables:
    *empty*

## The particle sets

`to_parcels_pset()` flattens the release positions to 2 plain lists, 1 entry
per particle: 30 grid points for the neighbour stencil, 4 arms each for the 2
auxiliary ones. The two lists are everything Parcels needs, and ingest
reattaches the advected positions to the grid by their order.

In [6]:
lon_0, lat_0 = seed.to_parcels_pset()
aux_lon_0, aux_lat_0 = aux_seed.to_parcels_pset()
scattered_lon_0, scattered_lat_0 = scattered_seed.to_parcels_pset()
print("neighbour particles:", len(lon_0))
print("auxiliary particles:", len(aux_lon_0))
print("unstructured auxiliary particles:", len(scattered_lon_0))

neighbour particles: 30
auxiliary particles: 120
unstructured auxiliary particles: 120


## Advection without Parcels

The particles sit still: $u = v = 0$ for 10 days. The flow map is the
identity, $\nabla F = I$, so the FTLE is zero wherever it is defined. A
non-zero window keeps $1/T$ finite.

In [7]:
lon_1, lat_1 = lon_0, lat_0
aux_lon_1, aux_lat_1 = aux_lon_0, aux_lat_0
scattered_lon_1, scattered_lat_1 = scattered_lon_0, scattered_lat_0

## The advected positions

`pset_to_flowmap` puts the flat positions back on the grid as `lon`/`lat`
beside the release positions `lon_0`/`lat_0`, and records `t0` and the signed
window `T` it derives from `t0` and `t1`. All three ingest through the same
call, and the datasets differ only where their release positions did.

In [8]:
flowmap = seed.pset_to_flowmap(lon=lon_1, lat=lat_1, t0=t0, t1=t1)
print(flowmap)
flowmap.ds

<NeighborFlowMap 6x5 grid, lon -25.00..-20.00, lat 15.00..20.00,
                 t0 2020-01-01T00:00:00, T +10.0 days>


<xarray.Dataset> Size: 2kB
Dimensions:   (i: 6, j: 5)
Coordinates:
  * i         (i) int64 48B 0 1 2 3 4 5
  * j         (j) int64 40B 0 1 2 3 4
    lon_grid  (i, j) float64 240B -25.0 -25.0 -25.0 -25.0 ... -20.0 -20.0 -20.0
    lat_grid  (i, j) float64 240B 15.0 16.25 17.5 18.75 ... 17.5 18.75 20.0
    lon_0     (i, j) float64 240B -25.0 -25.0 -25.0 -25.0 ... -20.0 -20.0 -20.0
    lat_0     (i, j) float64 240B 15.0 16.25 17.5 18.75 ... 17.5 18.75 20.0
    t0        datetime64[s] 8B 2020-01-01
    T         timedelta64[s] 8B 10 days
Data variables:
    lon       (i, j) float64 240B -25.0 -25.0 -25.0 -25.0 ... -20.0 -20.0 -20.0
    lat       (i, j) float64 240B 15.0 16.25 17.5 18.75 ... 17.5 18.75 20.0

In [9]:
aux_flowmap = aux_seed.pset_to_flowmap(lon=aux_lon_1, lat=aux_lat_1, t0=t0, t1=t1)
print(aux_flowmap)
aux_flowmap.ds

<AuxiliaryFlowMap 6x5 grid, lon -25.00..-20.00, lat 15.00..20.00,
                  t0 2020-01-01T00:00:00, T +10.0 days>


<xarray.Dataset> Size: 5kB
Dimensions:       (displacement: 4, i: 6, j: 5)
Coordinates:
  * displacement  (displacement) <U5 80B 'east' 'north' 'west' 'south'
    lon_0         (i, j, displacement) float64 960B -24.99 -25.0 ... -20.0
    lat_0         (i, j, displacement) float64 960B 15.0 15.01 ... 20.0 19.99
  * i             (i) int64 48B 0 1 2 3 4 5
  * j             (j) int64 40B 0 1 2 3 4
    lon_grid      (i, j) float64 240B -25.0 -25.0 -25.0 ... -20.0 -20.0 -20.0
    lat_grid      (i, j) float64 240B 15.0 16.25 17.5 18.75 ... 17.5 18.75 20.0
    t0            datetime64[s] 8B 2020-01-01
    T             timedelta64[s] 8B 10 days
Data variables:
    lon           (i, j, displacement) float64 960B -24.99 -25.0 ... -20.0
    lat           (i, j, displacement) float64 960B 15.0 15.01 ... 20.0 19.99

In [10]:
scattered_flowmap = scattered_seed.pset_to_flowmap(
    lon=scattered_lon_1, lat=scattered_lat_1, t0=t0, t1=t1
)
print(scattered_flowmap)
scattered_flowmap.ds

<UnstructuredAuxiliaryFlowMap 30 grid, lon -24.99..-20.01, lat 15.26..19.67,
                              t0 2020-01-01T00:00:00, T +10.0 days>


<xarray.Dataset> Size: 5kB
Dimensions:       (displacement: 4, grid_point: 30)
Coordinates:
  * displacement  (displacement) <U5 80B 'east' 'north' 'west' 'south'
    lon_0         (grid_point, displacement) float64 960B -21.81 ... -21.75
    lat_0         (grid_point, displacement) float64 960B 18.44 18.45 ... 15.25
  * grid_point    (grid_point) int64 240B 0 1 2 3 4 5 6 ... 23 24 25 26 27 28 29
    lon_grid      (grid_point) float64 240B -21.82 -23.65 ... -21.57 -21.75
    lat_grid      (grid_point) float64 240B 18.44 16.94 15.68 ... 16.15 15.26
    t0            datetime64[s] 8B 2020-01-01
    T             timedelta64[s] 8B 10 days
Data variables:
    lon           (grid_point, displacement) float64 960B -21.81 ... -21.75
    lat           (grid_point, displacement) float64 960B 18.44 18.45 ... 15.25

`grid_image` is the one place the datasets are reconciled. It holds the
advected position *of the grid point*, on the grid dims. The neighbour flow
map passes its single advected position through, while the auxiliary ones
take the centroid of their four advected arms.

In [11]:
aux_flowmap.grid_image

<xarray.Dataset> Size: 1kB
Dimensions:   (i: 6, j: 5)
Coordinates:
  * i         (i) int64 48B 0 1 2 3 4 5
  * j         (j) int64 40B 0 1 2 3 4
    lon_grid  (i, j) float64 240B -25.0 -25.0 -25.0 -25.0 ... -20.0 -20.0 -20.0
    lat_grid  (i, j) float64 240B 15.0 16.25 17.5 18.75 ... 17.5 18.75 20.0
    t0        datetime64[s] 8B 2020-01-01
    T         timedelta64[s] 8B 10 days
Data variables:
    lon       (i, j) float64 240B -25.0 -25.0 -25.0 -25.0 ... -20.0 -20.0 -20.0
    lat       (i, j) float64 240B 15.0 16.25 17.5 18.75 ... 17.5 18.75 20.0

## FTLE from all three

`ftle()` returns 1/s at the diagnostic grid points. All three give zero, but
they differ in where the FTLE is defined and in the dims it comes back on.

In [12]:
ftle = flowmap.ftle()
ftle

<xarray.DataArray 'ftle' (i: 6, j: 5)> Size: 240B
array([[nan, nan, nan, nan, nan],
       [nan,  0.,  0.,  0., nan],
       [nan,  0.,  0.,  0., nan],
       [nan,  0.,  0.,  0., nan],
       [nan,  0.,  0.,  0., nan],
       [nan, nan, nan, nan, nan]])
Coordinates:
  * i         (i) int64 48B 0 1 2 3 4 5
  * j         (j) int64 40B 0 1 2 3 4
    lon_grid  (i, j) float64 240B -25.0 -25.0 -25.0 -25.0 ... -20.0 -20.0 -20.0
    lat_grid  (i, j) float64 240B 15.0 16.25 17.5 18.75 ... 17.5 18.75 20.0
    t0        datetime64[s] 8B 2020-01-01
    T         timedelta64[s] 8B 10 days
Attributes:
    long_name:  finite-time Lyapunov exponent
    units:      1/s

In [13]:
aux_ftle = aux_flowmap.ftle()
aux_ftle

<xarray.DataArray 'ftle' (i: 6, j: 5)> Size: 240B
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])
Coordinates:
  * i         (i) int64 48B 0 1 2 3 4 5
  * j         (j) int64 40B 0 1 2 3 4
    lon_grid  (i, j) float64 240B -25.0 -25.0 -25.0 -25.0 ... -20.0 -20.0 -20.0
    lat_grid  (i, j) float64 240B 15.0 16.25 17.5 18.75 ... 17.5 18.75 20.0
    t0        datetime64[s] 8B 2020-01-01
    T         timedelta64[s] 8B 10 days
Attributes:
    long_name:  finite-time Lyapunov exponent
    units:      1/s

In [14]:
scattered_ftle = scattered_flowmap.ftle()
scattered_ftle

<xarray.DataArray 'ftle' (grid_point: 30)> Size: 240B
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
Coordinates:
  * grid_point  (grid_point) int64 240B 0 1 2 3 4 5 6 7 ... 23 24 25 26 27 28 29
    lon_grid    (grid_point) float64 240B -21.82 -23.65 -24.8 ... -21.57 -21.75
    lat_grid    (grid_point) float64 240B 18.44 16.94 15.68 ... 16.15 15.26
    t0          datetime64[s] 8B 2020-01-01
    T           timedelta64[s] 8B 10 days
Attributes:
    long_name:  finite-time Lyapunov exponent
    units:      1/s

In [15]:
print("neighbour: max |ftle| =", float(abs(ftle).max()))
print("auxiliary: max |ftle| =", float(abs(aux_ftle).max()))
print("unstructured: max |ftle| =", float(abs(scattered_ftle).max()))
print("neighbour NaN points:", int(ftle.isnull().sum()))
print("auxiliary NaN points:", int(aux_ftle.isnull().sum()))
print("unstructured NaN points:", int(scattered_ftle.isnull().sum()))

neighbour: max |ftle| = 0.0
auxiliary: max |ftle| = 0.0
unstructured: max |ftle| = 0.0
neighbour NaN points: 18
auxiliary NaN points: 0
unstructured NaN points: 0
